name: Docker CI pipeline
run-name: ${{github.actor}} is running out Docker CI pipeline
on: [push]
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code
        uses: actions/checkout@v6
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          config: .hadolint.yaml
      - name: Docker Build
        run: docker build -t ${{vars.DOCKERHUB_USERNAME}}/helloworld-python:v1 .
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{vars.DOCKERHUB_USERNAME}}/helloworld-python:v1'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push
        run: docker push ${{vars.DOCKERHUB_USERNAME}}/helloworld-python:v1

      - name: Docker run 
        run: docker run --name helloworld-python -itd -p 8080:8080 ${{vars.DOCKERHUB_USERNAME}}/helloworld-python:v1

      - name: view the container
        run: docker ps

  k8s-implementation:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: clone the code
        uses: actions/checkout@v6

      - name: start minikube
        uses: medyagh/setup-minikube@latest 

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Create a deployment
        run: |
          kubectl apply -f manifests/deployment.yaml
          kubectl apply -f manifests/service.yaml
          kubectl wait --for=condition=ready pod -l app=helloworld-python-deployment

      - name: view the deployment and service
        run: |
          kubectl get deployments
          kubectl get services    
